// apps/todo/react/src/app/todo/todo.tsx
import { TodoVM, TodoPresenter } from '@nx-clean/todo-presentation';
import React, { useEffect } from 'react';

import { injector } from '../app.provider';

import TodoFooter from './todo-footer/todo-footer';
import TodoHeader from './todo-header/todo-header';
import Todos from './todos/todos';

/* eslint-disable-next-line */
export interface TodoProps {}

const presenter = injector.get<TodoPresenter>(TodoPresenter);

export function Todo(props: TodoProps) {
  const [value, setValue] = React.useState('');
  const [state, setState] = React.useState<TodoVM[]>([]);
  const [buttonGroup, setButtonGroup] = React.useState('showAll');

  useEffect(() => {
    presenter.getAllTodos().subscribe(setState).unsubscribe();

    const subscription = presenter.todos$.subscribe(setState);

    return () => subscription.unsubscribe();
  }, []);

  function handleAddTodo(event: React.KeyboardEvent) {
    if (event.key === 'Enter') {
      presenter.addTodo(value);
      setValue('');
    }
  }

  function onToggleItem(input: HTMLInputElement, id: string) {
    if (input.checked) {
      presenter.markTodoAsCompleted(id);
    } else {
      presenter.markTodoAsActive(id);
    }
  }

  function onShowAll() {
    presenter.getAllTodos();
  }

  function onShowActive() {
    presenter.getActiveTodos();
  }

  function onShowCompleted() {
    presenter.getCompletedTodos();
  }

  function onClearCompleted() {
    presenter.removeCompletedTodos();
  }

  function onRemoveItem(todo: TodoVM) {
    presenter.removeTodo(todo.id);
  }

  function handleButtonGroup(
    event: React.MouseEvent<HTMLElement>,
    newAlignment: string
  ) {
    setButtonGroup(newAlignment);
  }

  return (
    <div>
      <TodoHeader />
      <main>
        <div className="form-control w-full max-w-xs">
          <label className="label">
            <span className="label-text">O que falta finalizar?</span>
          </label>
          <input
            id="outline-required"
            type="text"
            placeholder="Type here"
            className="input input-bordered w-full max-w-xs"
            name="task"
            autoFocus={true}
            value={value}
            onChange={(event) => setValue(event.target.value)}
            onKeyUp={(event) => handleAddTodo(event)}
          />
        </div>
        <div className="divider"></div>
        <Todos
          todos={state}
          handleToggleItem={onToggleItem}
          handleRemoveItem={onRemoveItem}
        />
        <div className="divider"></div>
      </main>
      <TodoFooter
        todos={state}
        buttonGroup={buttonGroup}
        handleShowAll={onShowAll}
        handleShowActive={onShowActive}
        handleShowCompleted={onShowCompleted}
        handleClearCompleted={onClearCompleted}
        handleButtonGroup={handleButtonGroup}
      />
      <footer className="w-full p-3 text-center">
        <a
          className="btn btn-ghost btn-sm rounded-btn m-auto"
          target="_blank"
          rel="noopener noreferrer"
          href="https://github.com/guiseek/nx-clean/blob/main/apps/todo/angular/src/app/todo"
        >
          Source code
        </a>
      </footer>
    </div>
  );
}

export default Todo;

// apps/todo/angular/src/app/todo/todo.component.ts
import { TodoPresenter, TodoVM } from '@nx-clean/todo-presentation';
import { Component } from '@angular/core';

@Component({
  selector: 'todo-angular',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.scss'],
})
export class TodoComponent {
  todos$ = this.todoApp.todos$;
  filter$ = this.todoApp.filter$;

  activeTodosCount$ = this.todoApp.activeTodosCount$;

  constructor(private todoApp: TodoPresenter) {
    this.todoApp.getAllTodos();
  }

  onAddItem(name: string) {
    this.todoApp.addTodo(name);
  }

  onCheckItem(todo: TodoVM) {
    this.todoApp.markTodoAsCompleted(todo.id);
  }

  onUncheckItem(todo: TodoVM) {
    this.todoApp.markTodoAsActive(todo.id);
  }

  onShowAll() {
    this.todoApp.getAllTodos();
  }

  onShowActive() {
    this.todoApp.getActiveTodos();
  }

  onShowCompleted() {
    this.todoApp.getCompletedTodos();
  }

  onClearCompleted() {
    this.todoApp.removeCompletedTodos();
  }

  onRemoveItem(todo: TodoVM) {
    this.todoApp.removeTodo(todo.id);
  }

  onToggleAllCompleted() {
    this.todoApp.markAllTodosAsCompleted();
  }

  onToggleAllActive() {
    this.todoApp.markAllTodosAsActive();
  }
}

<div class="navbar bg-base-300">
  <div class="navbar-start">
    <a href="/">
      <label tabindex="0" class="btn btn-ghost btn-circle">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="svg-icon"
          style="
            width: 1em;
            height: 1em;
            vertical-align: middle;
            fill: currentColor;
            overflow: hidden;
          "
          viewBox="0 0 1024 1024"
          version="1.1"
        >
          <path
            d="M657.706667 316.373333L597.333333 256 341.333333 512l256 256 60.373334-60.373333L462.08 512z"
          />
        </svg>
      </label>
      Back
    </a>
  </div>
  <div class="navbar-center">
    <h1>Angular - <span>Clean Architecture .design</span></h1>
  </div>
</div>

<main>
  <todo-header
    (addItem)="onAddItem($event)"
    (toggleAllCompleted)="onToggleAllCompleted()"
    (toggleAllActive)="onToggleAllActive()"
  >
  </todo-header>

  <todo-todos
    [todos]="todos$ | async"
    (checkItem)="onCheckItem($event)"
    (uncheckItem)="onUncheckItem($event)"
    (removeItem)="onRemoveItem($event)"
  >
  </todo-todos>

  <todo-footer
    [count]="activeTodosCount$ | async"
    [filter]="filter$ | async"
    (all)="onShowAll()"
    (active)="onShowActive()"
    (completed)="onShowCompleted()"
    (clearCompleted)="onClearCompleted()"
  >
  </todo-footer>
</main>

<footer class="w-full p-3 text-center">
  <a
    class="btn btn-ghost btn-sm rounded-btn m-auto"
    target="_blank"
    rel="noopener noreferrer"
    href="https://github.com/guiseek/nx-clean/blob/main/apps/todo/angular/src/app/todo"
  >
    Source code
  </a>
</footer>
