// apps/todo/react/src/app/todo/todo-item/todo-item.tsx
import { ReactComponent as DeleteIcon } from './deleteIcon.svg';

import { TodoVM } from '@nx-clean/todo-presentation';

export interface TodoItemProps {
  todo: TodoVM;
  handleToggleItem(input: HTMLInputElement, id: string): void;
  handleRemoveItem(id: TodoVM): void;
}

export function TodoItem({
  todo,
  handleToggleItem,
  handleRemoveItem,
}: TodoItemProps) {
  return (
    <div key={todo.id} className="form-control w-full max-w-xs justify-normal!">
      <label className="label cursor-pointer">
        <input
          aria-label={todo.name}
          type="checkbox"
          className="checkbox checkbox-primary"
          style={{ maxWidth: '25px' }}
          checked={todo.completed}
          onChange={(event) => handleToggleItem(event.target, todo.id)}
        />
        <span className="label-text"> {todo.name} </span>
        <button className="btn" onClick={() => handleRemoveItem(todo)}>
          <DeleteIcon />
        </button>
      </label>
    </div>
  );
}

export default TodoItem;

// apps/todo/angular/src/app/todo/todo-item/todo-item.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { TodoVM } from '@nx-clean/todo-presentation';
import { FormControl } from '@angular/forms';

@Component({
  selector: '[todo-item]',
  templateUrl: './todo-item.component.html',
})
export class TodoItemComponent {
  @Input() todo!: TodoVM;
  @Output() toggle = new EventEmitter<boolean>();
  @Output() remove = new EventEmitter();

  checkbox = new FormControl()

  onToggleItem(checked: boolean) {
    this.toggle.next(checked);
  }

  onRemoveItem() {
    this.remove.emit();
  }
}

<!-- <todo-checkbox
  [formControl]="checkbox"
  [checked]="todo.completed"
  (stateChange)="onToggleItem(checkbox.value)"
>
  {{ todo.name }}
</todo-checkbox> -->

<div class="form-control w-full max-w-xs justify-normal!">
  <label class="label cursor-pointer">
    <input
      type="checkbox"
      class="checkbox checkbox-primary"
      [formControl]="checkbox"
      [checked]="todo.completed"
      (stateChange)="onToggleItem(checkbox.value!)"
      />
    <span class="label-text"> {{ todo.name }} </span> 
    <button class="btn" (click)="onRemoveItem()">
      <svg xmlns="http://www.w3.org/2000/svg" class="svg-icon" style="width: 1em;height: 1em;vertical-align: middle;fill: currentColor;overflow: hidden;" viewBox="0 0 1024 1024" version="1.1"><path d="M341.333333 170.666667l42.666667-85.333334h256l42.666667 85.333334h213.333333v85.333333H128V170.666667h213.333333zM213.333333 298.666667h597.333334v554.666666a85.333333 85.333333 0 0 1-85.333334 85.333334H298.666667a85.333333 85.333333 0 0 1-85.333334-85.333334V298.666667z m85.333334 85.333333v469.333333h426.666666V384H298.666667z m85.333333 85.333333h85.333333v298.666667H384v-298.666667z m170.666667 0h85.333333v298.666667h-85.333333v-298.666667z"/></svg>
    </button>
  </label>
  
</div>
